import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..");

const pkgPath = path.join(root, "package.json");
const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
const version = pkg.version || "0.0.0";

// 1) src/generated/appVersion.js
const genDir = path.join(root, "src", "generated");
fs.mkdirSync(genDir, { recursive: true });
fs.writeFileSync(
  path.join(genDir, "appVersion.js"),
  `// auto-generated by scripts/gen-version.mjs\nexport const APP_VERSION = ${JSON.stringify(version)};\n`
);

// 2) public/version.json
const publicDir = path.join(root, "public");
fs.mkdirSync(publicDir, { recursive: true });
fs.writeFileSync(
  path.join(publicDir, "version.json"),
  JSON.stringify({ version }, null, 2) + "\n"
);

console.log(`[gen:version] version=${version}`);
