// scripts/write-version.mjs
import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const ROOT = process.cwd();

function readJson(p) {
  return JSON.parse(fs.readFileSync(p, "utf8"));
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeFile(filePath, contents) {
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, contents, "utf8");
}

try {
  const pkg = readJson(path.join(ROOT, "package.json"));
  const version = String(pkg.version || "0.0.0");
  const builtAt = new Date().toISOString();

  // 1) Public file (served from /version.json in dev + prod)
  const publicVersionPath = path.join(ROOT, "public", "version.json");
  writeFile(
    publicVersionPath,
    JSON.stringify({ version, builtAt }, null, 2) + "\n"
  );

  // 2) Importable constant so the app always knows its CURRENT_VERSION
  const generatedPath = path.join(ROOT, "src", "generated", "appVersion.js");
  writeFile(
    generatedPath,
    `// AUTO-GENERATED by scripts/write-version.mjs
export const APP_VERSION = ${JSON.stringify(version)};
export const BUILT_AT = ${JSON.stringify(builtAt)};
`
  );

  console.log(`[write-version] version=${version} builtAt=${builtAt}`);
} catch (err) {
  console.error("[write-version] failed:", err?.message || err);
  // Don't crash dev/build; just leave things as-is.
  process.exit(0);
}
