import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const root = path.resolve(__dirname, "..");
const pkgPath = path.join(root, "package.json");
const outDir = path.join(root, "src", "generated");
const outFile = path.join(outDir, "appVersion.js");

const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
const version = String(pkg.version || "0.0.0").trim();

fs.mkdirSync(outDir, { recursive: true });

const contents =
  `// AUTO-GENERATED by scripts/write-version.mjs\n` +
  `export const APP_VERSION = ${JSON.stringify(version)};\n`;

fs.writeFileSync(outFile, contents, "utf8");

console.log(`[version] wrote src/generated/appVersion.js = ${version}`);
